### ISSUE TITLE
Ordered Lists not Working

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/creativemag-pro#1]
https://themeisle.com/forums/reply/35081

**Comment by rodica-andronache** [comment]
@ineagu inchid?

**Comment by ineagu** [comment]
yep, we can close this theme and remove from w.org/site


On Thu, Apr 7, 2016 at 2:19 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> inchid?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/creativemag-pro/issues/1#issuecomment-206822324>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
